# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MoveFeature
                                 A QGIS plugin
 This plugin moves the features fro one location to another.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-10-06
        copyright            : (C) 2020 by Murat ÇALIŞKAN
        email                : caliskan.murat.20@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MoveFeature class from file MoveFeature.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .moving_feature import MoveFeature
    return MoveFeature(iface)
